# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt5GUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1309, 1084)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MainHeader = QtWidgets.QFrame(self.centralwidget)
        self.MainHeader.setMaximumSize(QtCore.QSize(16777215, 50))
        self.MainHeader.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.MainHeader.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainHeader.setObjectName("MainHeader")
        self.verticalLayout.addWidget(self.MainHeader)
        self.MainBody = QtWidgets.QFrame(self.centralwidget)
        self.MainBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBody.setObjectName("MainBody")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.MainBody)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.VideoPanel = QtWidgets.QFrame(self.MainBody)
        self.VideoPanel.setMinimumSize(QtCore.QSize(700, 1040))
        self.VideoPanel.setMaximumSize(QtCore.QSize(700, 1040))
        self.VideoPanel.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.VideoPanel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.VideoPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VideoPanel.setObjectName("VideoPanel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.VideoPanel)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ColorVideoFrame = QtWidgets.QFrame(self.VideoPanel)
        self.ColorVideoFrame.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.ColorVideoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ColorVideoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ColorVideoFrame.setObjectName("ColorVideoFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.ColorVideoFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.ColorVideo = QtWidgets.QLabel(self.ColorVideoFrame)
        self.ColorVideo.setMinimumSize(QtCore.QSize(640, 480))
        self.ColorVideo.setMaximumSize(QtCore.QSize(640, 480))
        self.ColorVideo.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.ColorVideo.setObjectName("ColorVideo")
        self.gridLayout.addWidget(self.ColorVideo, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.ColorVideoFrame)
        self.DepthVideoFrame = QtWidgets.QFrame(self.VideoPanel)
        self.DepthVideoFrame.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.DepthVideoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DepthVideoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DepthVideoFrame.setObjectName("DepthVideoFrame")
        self.DepthVideo = QtWidgets.QLabel(self.DepthVideoFrame)
        self.DepthVideo.setGeometry(QtCore.QRect(30, 20, 640, 480))
        self.DepthVideo.setMinimumSize(QtCore.QSize(640, 480))
        self.DepthVideo.setMaximumSize(QtCore.QSize(640, 480))
        self.DepthVideo.setStyleSheet("background-color: rgb(0,0,0);")
        self.DepthVideo.setObjectName("DepthVideo")
        self.verticalLayout_2.addWidget(self.DepthVideoFrame)
        self.horizontalLayout.addWidget(self.VideoPanel)
        self.MenuPanel = QtWidgets.QFrame(self.MainBody)
        self.MenuPanel.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.MenuPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MenuPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MenuPanel.setObjectName("MenuPanel")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.MenuPanel)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ColorMenuFrame = QtWidgets.QFrame(self.MenuPanel)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ColorMenuFrame.setFont(font)
        self.ColorMenuFrame.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.ColorMenuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ColorMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ColorMenuFrame.setObjectName("ColorMenuFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ColorMenuFrame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ColorTitleFrame = QtWidgets.QFrame(self.ColorMenuFrame)
        self.ColorTitleFrame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.ColorTitleFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ColorTitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ColorTitleFrame.setObjectName("ColorTitleFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ColorTitleFrame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.CVideoLabel = QtWidgets.QLabel(self.ColorTitleFrame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.CVideoLabel.setFont(font)
        self.CVideoLabel.setObjectName("CVideoLabel")
        self.verticalLayout_6.addWidget(self.CVideoLabel, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.ColorTitleFrame)
        self.ColorButtonFrame = QtWidgets.QFrame(self.ColorMenuFrame)
        self.ColorButtonFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.ColorButtonFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ColorButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ColorButtonFrame.setObjectName("ColorButtonFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ColorButtonFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.StartColorVideo = QtWidgets.QPushButton(self.ColorButtonFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.StartColorVideo.setFont(font)
        self.StartColorVideo.setStyleSheet("background-color: rgb(78, 154, 6);")
        self.StartColorVideo.setObjectName("StartColorVideo")
        self.gridLayout_3.addWidget(self.StartColorVideo, 0, 0, 1, 1)
        self.StopColorVideo = QtWidgets.QPushButton(self.ColorButtonFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.StopColorVideo.setFont(font)
        self.StopColorVideo.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.StopColorVideo.setObjectName("StopColorVideo")
        self.gridLayout_3.addWidget(self.StopColorVideo, 0, 1, 1, 1)
        self.SaveColorPic = QtWidgets.QPushButton(self.ColorButtonFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.SaveColorPic.setFont(font)
        self.SaveColorPic.setObjectName("SaveColorPic")
        self.gridLayout_3.addWidget(self.SaveColorPic, 0, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.ColorButtonFrame)
        self.ColorDropdownFrame = QtWidgets.QFrame(self.ColorMenuFrame)
        self.ColorDropdownFrame.setMinimumSize(QtCore.QSize(603, 387))
        self.ColorDropdownFrame.setMaximumSize(QtCore.QSize(603, 387))
        self.ColorDropdownFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ColorDropdownFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ColorDropdownFrame.setObjectName("ColorDropdownFrame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.ColorDropdownFrame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.PointDistanceFrame = QtWidgets.QFrame(self.ColorDropdownFrame)
        self.PointDistanceFrame.setMinimumSize(QtCore.QSize(603, 44))
        self.PointDistanceFrame.setMaximumSize(QtCore.QSize(603, 44))
        self.PointDistanceFrame.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.PointDistanceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PointDistanceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PointDistanceFrame.setObjectName("PointDistanceFrame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.PointDistanceFrame)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.PointTitleFrame = QtWidgets.QFrame(self.PointDistanceFrame)
        self.PointTitleFrame.setMinimumSize(QtCore.QSize(0, 44))
        self.PointTitleFrame.setMaximumSize(QtCore.QSize(16777215, 44))
        self.PointTitleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PointTitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PointTitleFrame.setObjectName("PointTitleFrame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.PointTitleFrame)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.ExpandPoint = QtWidgets.QPushButton(self.PointTitleFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ExpandPoint.setFont(font)
        self.ExpandPoint.setStyleSheet("text-align: left")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Expand/ExpandArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.ExpandPoint.setIcon(icon)
        self.ExpandPoint.setIconSize(QtCore.QSize(40, 40))
        self.ExpandPoint.setObjectName("ExpandPoint")
        self.verticalLayout_13.addWidget(self.ExpandPoint)
        self.verticalLayout_9.addWidget(self.PointTitleFrame)
        self.PointFunctionFrame = QtWidgets.QFrame(self.PointDistanceFrame)
        self.PointFunctionFrame.setStyleSheet("")
        self.PointFunctionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PointFunctionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PointFunctionFrame.setObjectName("PointFunctionFrame")
        self.label = QtWidgets.QLabel(self.PointFunctionFrame)
        self.label.setGeometry(QtCore.QRect(0, 10, 601, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.PointX = QtWidgets.QTextEdit(self.PointFunctionFrame)
        self.PointX.setGeometry(QtCore.QRect(50, 60, 104, 31))
        self.PointX.setObjectName("PointX")
        self.PointY = QtWidgets.QTextEdit(self.PointFunctionFrame)
        self.PointY.setGeometry(QtCore.QRect(240, 60, 104, 31))
        self.PointY.setObjectName("PointY")
        self.label_2 = QtWidgets.QLabel(self.PointFunctionFrame)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.PointFunctionFrame)
        self.label_3.setGeometry(QtCore.QRect(210, 70, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.PointFunctionFrame)
        self.label_4.setGeometry(QtCore.QRect(380, 70, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.PointDistance = QtWidgets.QLabel(self.PointFunctionFrame)
        self.PointDistance.setGeometry(QtCore.QRect(500, 70, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PointDistance.setFont(font)
        self.PointDistance.setText("")
        self.PointDistance.setObjectName("PointDistance")
        self.ClearPointDistance = QtWidgets.QPushButton(self.PointFunctionFrame)
        self.ClearPointDistance.setGeometry(QtCore.QRect(320, 130, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ClearPointDistance.setFont(font)
        self.ClearPointDistance.setObjectName("ClearPointDistance")
        self.CalculatePointDistance = QtWidgets.QPushButton(self.PointFunctionFrame)
        self.CalculatePointDistance.setGeometry(QtCore.QRect(180, 130, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.CalculatePointDistance.setFont(font)
        self.CalculatePointDistance.setObjectName("CalculatePointDistance")
        self.verticalLayout_9.addWidget(self.PointFunctionFrame)
        self.verticalLayout_8.addWidget(self.PointDistanceFrame)
        self.LineDistanceFrame = QtWidgets.QFrame(self.ColorDropdownFrame)
        self.LineDistanceFrame.setMinimumSize(QtCore.QSize(603, 44))
        self.LineDistanceFrame.setMaximumSize(QtCore.QSize(603, 44))
        self.LineDistanceFrame.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.LineDistanceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LineDistanceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LineDistanceFrame.setObjectName("LineDistanceFrame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.LineDistanceFrame)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.LineTitleFrame = QtWidgets.QFrame(self.LineDistanceFrame)
        self.LineTitleFrame.setMinimumSize(QtCore.QSize(0, 44))
        self.LineTitleFrame.setMaximumSize(QtCore.QSize(16777215, 44))
        self.LineTitleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LineTitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LineTitleFrame.setObjectName("LineTitleFrame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.LineTitleFrame)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.ExpandLine = QtWidgets.QPushButton(self.LineTitleFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ExpandLine.setFont(font)
        self.ExpandLine.setStyleSheet("text-align: left")
        self.ExpandLine.setIcon(icon)
        self.ExpandLine.setIconSize(QtCore.QSize(40, 40))
        self.ExpandLine.setObjectName("ExpandLine")
        self.verticalLayout_14.addWidget(self.ExpandLine)
        self.verticalLayout_10.addWidget(self.LineTitleFrame)
        self.LineFunctionFrame = QtWidgets.QFrame(self.LineDistanceFrame)
        self.LineFunctionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LineFunctionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LineFunctionFrame.setObjectName("LineFunctionFrame")
        self.DrawLine = QtWidgets.QPushButton(self.LineFunctionFrame)
        self.DrawLine.setGeometry(QtCore.QRect(440, 90, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DrawLine.setFont(font)
        self.DrawLine.setObjectName("DrawLine")
        self.label_5 = QtWidgets.QLabel(self.LineFunctionFrame)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 571, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.LineX1 = QtWidgets.QTextEdit(self.LineFunctionFrame)
        self.LineX1.setGeometry(QtCore.QRect(150, 70, 104, 31))
        self.LineX1.setObjectName("LineX1")
        self.LineY1 = QtWidgets.QTextEdit(self.LineFunctionFrame)
        self.LineY1.setGeometry(QtCore.QRect(310, 70, 104, 31))
        self.LineY1.setObjectName("LineY1")
        self.LineX2 = QtWidgets.QTextEdit(self.LineFunctionFrame)
        self.LineX2.setGeometry(QtCore.QRect(150, 110, 104, 31))
        self.LineX2.setObjectName("LineX2")
        self.LineY2 = QtWidgets.QTextEdit(self.LineFunctionFrame)
        self.LineY2.setGeometry(QtCore.QRect(310, 110, 104, 31))
        self.LineY2.setObjectName("LineY2")
        self.label_8 = QtWidgets.QLabel(self.LineFunctionFrame)
        self.label_8.setGeometry(QtCore.QRect(110, 80, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.LineFunctionFrame)
        self.label_9.setGeometry(QtCore.QRect(110, 120, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.LineFunctionFrame)
        self.label_10.setGeometry(QtCore.QRect(270, 80, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.LineFunctionFrame)
        self.label_11.setGeometry(QtCore.QRect(270, 120, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.LineFunctionFrame)
        self.label_12.setGeometry(QtCore.QRect(20, 160, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.LineDistance = QtWidgets.QLabel(self.LineFunctionFrame)
        self.LineDistance.setGeometry(QtCore.QRect(150, 160, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.LineDistance.setFont(font)
        self.LineDistance.setText("")
        self.LineDistance.setObjectName("LineDistance")
        self.CalculateLineDistance = QtWidgets.QPushButton(self.LineFunctionFrame)
        self.CalculateLineDistance.setGeometry(QtCore.QRect(310, 160, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.CalculateLineDistance.setFont(font)
        self.CalculateLineDistance.setObjectName("CalculateLineDistance")
        self.ClearLineDistance = QtWidgets.QPushButton(self.LineFunctionFrame)
        self.ClearLineDistance.setGeometry(QtCore.QRect(440, 160, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ClearLineDistance.setFont(font)
        self.ClearLineDistance.setObjectName("ClearLineDistance")
        self.LinePoint1 = QtWidgets.QPushButton(self.LineFunctionFrame)
        self.LinePoint1.setGeometry(QtCore.QRect(10, 70, 89, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.LinePoint1.setFont(font)
        self.LinePoint1.setObjectName("LinePoint1")
        self.LinePoint2 = QtWidgets.QPushButton(self.LineFunctionFrame)
        self.LinePoint2.setGeometry(QtCore.QRect(10, 110, 89, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.LinePoint2.setFont(font)
        self.LinePoint2.setObjectName("LinePoint2")
        self.verticalLayout_10.addWidget(self.LineFunctionFrame)
        self.verticalLayout_8.addWidget(self.LineDistanceFrame)
        self.MultiplePointsFrame = QtWidgets.QFrame(self.ColorDropdownFrame)
        self.MultiplePointsFrame.setMinimumSize(QtCore.QSize(603, 44))
        self.MultiplePointsFrame.setMaximumSize(QtCore.QSize(603, 44))
        self.MultiplePointsFrame.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.MultiplePointsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MultiplePointsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MultiplePointsFrame.setObjectName("MultiplePointsFrame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.MultiplePointsFrame)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.MultipleTitleFrame = QtWidgets.QFrame(self.MultiplePointsFrame)
        self.MultipleTitleFrame.setMinimumSize(QtCore.QSize(0, 44))
        self.MultipleTitleFrame.setMaximumSize(QtCore.QSize(16777215, 44))
        self.MultipleTitleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MultipleTitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MultipleTitleFrame.setObjectName("MultipleTitleFrame")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.MultipleTitleFrame)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.ExpandMultiple = QtWidgets.QPushButton(self.MultipleTitleFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ExpandMultiple.setFont(font)
        self.ExpandMultiple.setStyleSheet("text-align: left")
        self.ExpandMultiple.setIcon(icon)
        self.ExpandMultiple.setIconSize(QtCore.QSize(40, 40))
        self.ExpandMultiple.setObjectName("ExpandMultiple")
        self.verticalLayout_15.addWidget(self.ExpandMultiple)
        self.verticalLayout_11.addWidget(self.MultipleTitleFrame)
        self.MultipleFunctionFrame = QtWidgets.QFrame(self.MultiplePointsFrame)
        self.MultipleFunctionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MultipleFunctionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MultipleFunctionFrame.setObjectName("MultipleFunctionFrame")
        self.pushButton_3 = QtWidgets.QPushButton(self.MultipleFunctionFrame)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 10, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_11.addWidget(self.MultipleFunctionFrame)
        self.verticalLayout_8.addWidget(self.MultiplePointsFrame)
        self.RadiusFrame = QtWidgets.QFrame(self.ColorDropdownFrame)
        self.RadiusFrame.setMinimumSize(QtCore.QSize(603, 44))
        self.RadiusFrame.setMaximumSize(QtCore.QSize(603, 44))
        self.RadiusFrame.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.RadiusFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RadiusFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RadiusFrame.setObjectName("RadiusFrame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.RadiusFrame)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.RadiusTitleFrame = QtWidgets.QFrame(self.RadiusFrame)
        self.RadiusTitleFrame.setMinimumSize(QtCore.QSize(0, 44))
        self.RadiusTitleFrame.setMaximumSize(QtCore.QSize(16777215, 44))
        self.RadiusTitleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RadiusTitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RadiusTitleFrame.setObjectName("RadiusTitleFrame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.RadiusTitleFrame)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.ExpandRadius = QtWidgets.QPushButton(self.RadiusTitleFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ExpandRadius.setFont(font)
        self.ExpandRadius.setStyleSheet("text-align: left")
        self.ExpandRadius.setIcon(icon)
        self.ExpandRadius.setIconSize(QtCore.QSize(40, 40))
        self.ExpandRadius.setObjectName("ExpandRadius")
        self.verticalLayout_16.addWidget(self.ExpandRadius)
        self.verticalLayout_12.addWidget(self.RadiusTitleFrame)
        self.RadiusFunctionFrame = QtWidgets.QFrame(self.RadiusFrame)
        self.RadiusFunctionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RadiusFunctionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RadiusFunctionFrame.setObjectName("RadiusFunctionFrame")
        self.pushButton_4 = QtWidgets.QPushButton(self.RadiusFunctionFrame)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 10, 89, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_12.addWidget(self.RadiusFunctionFrame)
        self.verticalLayout_8.addWidget(self.RadiusFrame)
        self.SpacerFrame = QtWidgets.QFrame(self.ColorDropdownFrame)
        self.SpacerFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.SpacerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SpacerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SpacerFrame.setObjectName("SpacerFrame")
        self.verticalLayout_8.addWidget(self.SpacerFrame)
        self.verticalLayout_4.addWidget(self.ColorDropdownFrame)
        self.verticalLayout_3.addWidget(self.ColorMenuFrame)
        self.DepthMenuFrame = QtWidgets.QFrame(self.MenuPanel)
        self.DepthMenuFrame.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.DepthMenuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DepthMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DepthMenuFrame.setObjectName("DepthMenuFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.DepthMenuFrame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.DepthTitleFrame = QtWidgets.QFrame(self.DepthMenuFrame)
        self.DepthTitleFrame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.DepthTitleFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DepthTitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DepthTitleFrame.setObjectName("DepthTitleFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.DepthTitleFrame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.DVideoLabel = QtWidgets.QLabel(self.DepthTitleFrame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.DVideoLabel.setFont(font)
        self.DVideoLabel.setObjectName("DVideoLabel")
        self.verticalLayout_7.addWidget(self.DVideoLabel, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.DepthTitleFrame)
        self.DepthButtonFrame = QtWidgets.QFrame(self.DepthMenuFrame)
        self.DepthButtonFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.DepthButtonFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DepthButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DepthButtonFrame.setObjectName("DepthButtonFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.DepthButtonFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.StartDepthVideo = QtWidgets.QPushButton(self.DepthButtonFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.StartDepthVideo.setFont(font)
        self.StartDepthVideo.setStyleSheet("background-color: rgb(78, 154, 6);")
        self.StartDepthVideo.setObjectName("StartDepthVideo")
        self.gridLayout_2.addWidget(self.StartDepthVideo, 0, 0, 1, 1)
        self.StopDepthVideo = QtWidgets.QPushButton(self.DepthButtonFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.StopDepthVideo.setFont(font)
        self.StopDepthVideo.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.StopDepthVideo.setObjectName("StopDepthVideo")
        self.gridLayout_2.addWidget(self.StopDepthVideo, 0, 1, 1, 1)
        self.SaveDepthPic = QtWidgets.QPushButton(self.DepthButtonFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.SaveDepthPic.setFont(font)
        self.SaveDepthPic.setObjectName("SaveDepthPic")
        self.gridLayout_2.addWidget(self.SaveDepthPic, 0, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.DepthButtonFrame)
        self.DepthDropdownFrame = QtWidgets.QFrame(self.DepthMenuFrame)
        self.DepthDropdownFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DepthDropdownFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DepthDropdownFrame.setObjectName("DepthDropdownFrame")
        self.verticalLayout_5.addWidget(self.DepthDropdownFrame)
        self.verticalLayout_3.addWidget(self.DepthMenuFrame)
        self.horizontalLayout.addWidget(self.MenuPanel)
        self.verticalLayout.addWidget(self.MainBody)
        self.MainFooter = QtWidgets.QFrame(self.centralwidget)
        self.MainFooter.setMaximumSize(QtCore.QSize(16777215, 50))
        self.MainFooter.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.MainFooter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFooter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFooter.setObjectName("MainFooter")
        self.verticalLayout.addWidget(self.MainFooter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1309, 22))
        self.menubar.setObjectName("menubar")
        self.menuMain_Page_Remove = QtWidgets.QMenu(self.menubar)
        self.menuMain_Page_Remove.setObjectName("menuMain_Page_Remove")
        self.menuSub_Page_Remove = QtWidgets.QMenu(self.menubar)
        self.menuSub_Page_Remove.setObjectName("menuSub_Page_Remove")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuMain_Page_Remove.menuAction())
        self.menubar.addAction(self.menuSub_Page_Remove.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ColorVideo.setText(_translate("MainWindow", "ColorVideo"))
        self.DepthVideo.setText(_translate("MainWindow", "DepthVideo"))
        self.CVideoLabel.setText(_translate("MainWindow", "Color Video Stream"))
        self.StartColorVideo.setText(_translate("MainWindow", "Start"))
        self.StopColorVideo.setText(_translate("MainWindow", "Stop"))
        self.SaveColorPic.setText(_translate("MainWindow", "Save Picture"))
        self.ExpandPoint.setText(_translate("MainWindow", "Single Point Distance"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Enter (X,Y) coordinate or click a point on the video feeds then click calculate.<br/>  The center point is (320, 240).</p></body></html>"))
        self.PointX.setPlaceholderText(_translate("MainWindow", "320"))
        self.PointY.setPlaceholderText(_translate("MainWindow", "240"))
        self.label_2.setText(_translate("MainWindow", "X:"))
        self.label_3.setText(_translate("MainWindow", "Y:"))
        self.label_4.setText(_translate("MainWindow", "Distance(m):"))
        self.ClearPointDistance.setText(_translate("MainWindow", "Clear"))
        self.CalculatePointDistance.setText(_translate("MainWindow", "Calculate"))
        self.ExpandLine.setText(_translate("MainWindow", "Line Distance"))
        self.DrawLine.setText(_translate("MainWindow", "Draw Line"))
        self.label_5.setText(_translate("MainWindow", "Enter two X,Y coordinates or click the button to draw a line between two \n"
"points on the color video stream."))
        self.label_8.setText(_translate("MainWindow", "X1:"))
        self.label_9.setText(_translate("MainWindow", "X2:"))
        self.label_10.setText(_translate("MainWindow", "Y1: "))
        self.label_11.setText(_translate("MainWindow", "Y2:"))
        self.label_12.setText(_translate("MainWindow", "Distance (m):"))
        self.CalculateLineDistance.setText(_translate("MainWindow", "Calculate"))
        self.ClearLineDistance.setText(_translate("MainWindow", "Clear"))
        self.LinePoint1.setText(_translate("MainWindow", "Point 1:"))
        self.LinePoint2.setText(_translate("MainWindow", "Point 2:"))
        self.ExpandMultiple.setText(_translate("MainWindow", "Multiple Points Distance"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.ExpandRadius.setText(_translate("MainWindow", "Radius Distance"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.DVideoLabel.setText(_translate("MainWindow", "Depth Video Stream"))
        self.StartDepthVideo.setText(_translate("MainWindow", "Start"))
        self.StopDepthVideo.setText(_translate("MainWindow", "Stop"))
        self.SaveDepthPic.setText(_translate("MainWindow", "SavePicture"))
        self.menuMain_Page_Remove.setTitle(_translate("MainWindow", "Main Page (Remove?)"))
        self.menuSub_Page_Remove.setTitle(_translate("MainWindow", "Sub-Page (Remove?)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
