# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt5GUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1309, 1194)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MainHeader = QtWidgets.QFrame(self.centralwidget)
        self.MainHeader.setMaximumSize(QtCore.QSize(16777215, 50))
        self.MainHeader.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.MainHeader.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainHeader.setObjectName("MainHeader")
        self.verticalLayout.addWidget(self.MainHeader)
        self.MainBody = QtWidgets.QFrame(self.centralwidget)
        self.MainBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBody.setObjectName("MainBody")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.MainBody)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.VideoPanel = QtWidgets.QFrame(self.MainBody)
        self.VideoPanel.setMinimumSize(QtCore.QSize(700, 1150))
        self.VideoPanel.setMaximumSize(QtCore.QSize(700, 1150))
        self.VideoPanel.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.VideoPanel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.VideoPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VideoPanel.setObjectName("VideoPanel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.VideoPanel)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ColorVideoFrame = QtWidgets.QFrame(self.VideoPanel)
        self.ColorVideoFrame.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.ColorVideoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ColorVideoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ColorVideoFrame.setObjectName("ColorVideoFrame")
        self.ColorVideo = QtWidgets.QLabel(self.ColorVideoFrame)
        self.ColorVideo.setGeometry(QtCore.QRect(30, 70, 640, 480))
        self.ColorVideo.setMinimumSize(QtCore.QSize(640, 480))
        self.ColorVideo.setMaximumSize(QtCore.QSize(640, 480))
        self.ColorVideo.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.ColorVideo.setObjectName("ColorVideo")
        self.ColorTitleFrame = QtWidgets.QFrame(self.ColorVideoFrame)
        self.ColorTitleFrame.setGeometry(QtCore.QRect(50, 0, 603, 70))
        self.ColorTitleFrame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.ColorTitleFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ColorTitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ColorTitleFrame.setObjectName("ColorTitleFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ColorTitleFrame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.CVideoLabel = QtWidgets.QLabel(self.ColorTitleFrame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.CVideoLabel.setFont(font)
        self.CVideoLabel.setObjectName("CVideoLabel")
        self.verticalLayout_6.addWidget(self.CVideoLabel, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.ColorVideoFrame)
        self.DepthVideoFrame = QtWidgets.QFrame(self.VideoPanel)
        self.DepthVideoFrame.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.DepthVideoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DepthVideoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DepthVideoFrame.setObjectName("DepthVideoFrame")
        self.DepthVideo = QtWidgets.QLabel(self.DepthVideoFrame)
        self.DepthVideo.setGeometry(QtCore.QRect(30, 70, 640, 480))
        self.DepthVideo.setMinimumSize(QtCore.QSize(640, 480))
        self.DepthVideo.setMaximumSize(QtCore.QSize(640, 480))
        self.DepthVideo.setStyleSheet("background-color: rgb(0,0,0);")
        self.DepthVideo.setObjectName("DepthVideo")
        self.DepthTitleFrame = QtWidgets.QFrame(self.DepthVideoFrame)
        self.DepthTitleFrame.setGeometry(QtCore.QRect(40, 0, 603, 70))
        self.DepthTitleFrame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.DepthTitleFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DepthTitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DepthTitleFrame.setObjectName("DepthTitleFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.DepthTitleFrame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.DVideoLabel = QtWidgets.QLabel(self.DepthTitleFrame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.DVideoLabel.setFont(font)
        self.DVideoLabel.setObjectName("DVideoLabel")
        self.verticalLayout_7.addWidget(self.DVideoLabel, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.DepthVideoFrame)
        self.horizontalLayout.addWidget(self.VideoPanel)
        self.MenuPanel = QtWidgets.QFrame(self.MainBody)
        self.MenuPanel.setMaximumSize(QtCore.QSize(16777215, 1200))
        self.MenuPanel.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.MenuPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MenuPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MenuPanel.setObjectName("MenuPanel")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.MenuPanel)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ColorMenuFrame = QtWidgets.QFrame(self.MenuPanel)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ColorMenuFrame.setFont(font)
        self.ColorMenuFrame.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.ColorMenuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ColorMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ColorMenuFrame.setObjectName("ColorMenuFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ColorMenuFrame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.DataInputFrame = QtWidgets.QFrame(self.ColorMenuFrame)
        self.DataInputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DataInputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DataInputFrame.setObjectName("DataInputFrame")
        self.DataControlsButtons = QtWidgets.QFrame(self.DataInputFrame)
        self.DataControlsButtons.setGeometry(QtCore.QRect(0, 0, 601, 100))
        self.DataControlsButtons.setMinimumSize(QtCore.QSize(0, 100))
        self.DataControlsButtons.setMaximumSize(QtCore.QSize(16777215, 100))
        self.DataControlsButtons.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.DataControlsButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DataControlsButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DataControlsButtons.setObjectName("DataControlsButtons")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.DataControlsButtons)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_14 = QtWidgets.QLabel(self.DataControlsButtons)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_20.addWidget(self.label_14)
        self.frame_2 = QtWidgets.QFrame(self.DataControlsButtons)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 44))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 44))
        self.frame_2.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.LiveDataInput = QtWidgets.QPushButton(self.frame_2)
        self.LiveDataInput.setGeometry(QtCore.QRect(150, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LiveDataInput.setFont(font)
        self.LiveDataInput.setStyleSheet("background-color: rgb(194, 232, 161);")
        self.LiveDataInput.setObjectName("LiveDataInput")
        self.SavedDataInput = QtWidgets.QPushButton(self.frame_2)
        self.SavedDataInput.setGeometry(QtCore.QRect(300, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SavedDataInput.setFont(font)
        self.SavedDataInput.setObjectName("SavedDataInput")
        self.verticalLayout_20.addWidget(self.frame_2)
        self.DataInputDropdown = QtWidgets.QFrame(self.DataInputFrame)
        self.DataInputDropdown.setGeometry(QtCore.QRect(0, 99, 611, 471))
        self.DataInputDropdown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DataInputDropdown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DataInputDropdown.setObjectName("DataInputDropdown")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.DataInputDropdown)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(1)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.VideoControlsFrame = QtWidgets.QFrame(self.DataInputDropdown)
        self.VideoControlsFrame.setMinimumSize(QtCore.QSize(0, 44))
        self.VideoControlsFrame.setMaximumSize(QtCore.QSize(16777215, 44))
        self.VideoControlsFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VideoControlsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VideoControlsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VideoControlsFrame.setObjectName("VideoControlsFrame")
        self.frame_6 = QtWidgets.QFrame(self.VideoControlsFrame)
        self.frame_6.setGeometry(QtCore.QRect(0, 50, 601, 96))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_18.addWidget(self.label_7)
        self.ColorButtonFrame = QtWidgets.QFrame(self.frame_6)
        self.ColorButtonFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.ColorButtonFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ColorButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ColorButtonFrame.setObjectName("ColorButtonFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ColorButtonFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.StartColorVideo = QtWidgets.QPushButton(self.ColorButtonFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.StartColorVideo.setFont(font)
        self.StartColorVideo.setStyleSheet("background-color: rgb(78, 154, 6);")
        self.StartColorVideo.setObjectName("StartColorVideo")
        self.gridLayout_3.addWidget(self.StartColorVideo, 0, 0, 1, 1)
        self.StopColorVideo = QtWidgets.QPushButton(self.ColorButtonFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.StopColorVideo.setFont(font)
        self.StopColorVideo.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.StopColorVideo.setObjectName("StopColorVideo")
        self.gridLayout_3.addWidget(self.StopColorVideo, 0, 1, 1, 1)
        self.verticalLayout_18.addWidget(self.ColorButtonFrame)
        self.frame_7 = QtWidgets.QFrame(self.VideoControlsFrame)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 601, 40))
        self.frame_7.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.LiveVideoExpand = QtWidgets.QPushButton(self.frame_7)
        self.LiveVideoExpand.setGeometry(QtCore.QRect(0, 0, 601, 40))
        self.LiveVideoExpand.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LiveVideoExpand.setFont(font)
        self.LiveVideoExpand.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LiveVideoExpand.setStyleSheet("text-align: left")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Expand/ExpandArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LiveVideoExpand.setIcon(icon)
        self.LiveVideoExpand.setIconSize(QtCore.QSize(40, 40))
        self.LiveVideoExpand.setDefault(False)
        self.LiveVideoExpand.setObjectName("LiveVideoExpand")
        self.verticalLayout_21.addWidget(self.VideoControlsFrame)
        self.SavedDataFrame = QtWidgets.QFrame(self.DataInputDropdown)
        self.SavedDataFrame.setMinimumSize(QtCore.QSize(0, 44))
        self.SavedDataFrame.setMaximumSize(QtCore.QSize(16777215, 44))
        self.SavedDataFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SavedDataFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SavedDataFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SavedDataFrame.setObjectName("SavedDataFrame")
        self.frame_4 = QtWidgets.QFrame(self.SavedDataFrame)
        self.frame_4.setGeometry(QtCore.QRect(0, 47, 601, 101))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_19.addWidget(self.label_6)
        self.LoadDataButton = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LoadDataButton.setFont(font)
        self.LoadDataButton.setStyleSheet("background-color: rgb(136, 234, 253);")
        self.LoadDataButton.setObjectName("LoadDataButton")
        self.verticalLayout_19.addWidget(self.LoadDataButton)
        self.frame_5 = QtWidgets.QFrame(self.SavedDataFrame)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 601, 40))
        self.frame_5.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.SavedDataExpand = QtWidgets.QPushButton(self.frame_5)
        self.SavedDataExpand.setGeometry(QtCore.QRect(0, 0, 601, 40))
        self.SavedDataExpand.setMinimumSize(QtCore.QSize(0, 0))
        self.SavedDataExpand.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SavedDataExpand.setFont(font)
        self.SavedDataExpand.setStyleSheet("text-align: left")
        self.SavedDataExpand.setIcon(icon)
        self.SavedDataExpand.setIconSize(QtCore.QSize(40, 40))
        self.SavedDataExpand.setObjectName("SavedDataExpand")
        self.slider = QtWidgets.QSlider(self.SavedDataFrame)
        self.slider.setGeometry(QtCore.QRect(120, 160, 471, 20))
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.Play = QtWidgets.QPushButton(self.SavedDataFrame)
        self.Play.setGeometry(QtCore.QRect(20, 150, 31, 31))
        self.Play.setText("")
        self.Play.setObjectName("Play")
        self.Pause = QtWidgets.QPushButton(self.SavedDataFrame)
        self.Pause.setGeometry(QtCore.QRect(70, 150, 31, 31))
        self.Pause.setText("")
        self.Pause.setObjectName("Pause")
        self.verticalLayout_21.addWidget(self.SavedDataFrame)
        self.SavePicFrame = QtWidgets.QFrame(self.DataInputDropdown)
        self.SavePicFrame.setMinimumSize(QtCore.QSize(0, 44))
        self.SavePicFrame.setMaximumSize(QtCore.QSize(16777215, 44))
        self.SavePicFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SavePicFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SavePicFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SavePicFrame.setObjectName("SavePicFrame")
        self.frame_8 = QtWidgets.QFrame(self.SavePicFrame)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 601, 40))
        self.frame_8.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.SavePicExpand = QtWidgets.QPushButton(self.frame_8)
        self.SavePicExpand.setGeometry(QtCore.QRect(0, 0, 601, 40))
        self.SavePicExpand.setMinimumSize(QtCore.QSize(0, 40))
        self.SavePicExpand.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SavePicExpand.setFont(font)
        self.SavePicExpand.setStyleSheet("text-align: left")
        self.SavePicExpand.setIcon(icon)
        self.SavePicExpand.setIconSize(QtCore.QSize(40, 40))
        self.SavePicExpand.setObjectName("SavePicExpand")
        self.frame_3 = QtWidgets.QFrame(self.SavePicFrame)
        self.frame_3.setGeometry(QtCore.QRect(10, 120, 581, 61))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SaveDepthPic = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.SaveDepthPic.setFont(font)
        self.SaveDepthPic.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(9, 41, 4, 100), stop:0.085 rgba(2, 79, 0, 100), stop:0.19 rgba(50, 147, 22, 100), stop:0.275 rgba(236, 191, 49, 100), stop:0.39 rgba(243, 61, 34, 100), stop:0.555 rgba(135, 81, 60, 100), stop:0.667 rgba(121, 75, 255, 100), stop:0.825 rgba(164, 255, 244, 100), stop:0.885 rgba(104, 222, 71, 100), stop:1 rgba(93, 128, 0, 100));")
        self.SaveDepthPic.setObjectName("SaveDepthPic")
        self.horizontalLayout_2.addWidget(self.SaveDepthPic)
        self.SaveColorPic = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.SaveColorPic.setFont(font)
        self.SaveColorPic.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.SaveColorPic.setObjectName("SaveColorPic")
        self.horizontalLayout_2.addWidget(self.SaveColorPic)
        self.label_15 = QtWidgets.QLabel(self.SavePicFrame)
        self.label_15.setGeometry(QtCore.QRect(10, 50, 581, 68))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_21.addWidget(self.SavePicFrame)
        self.SaveDatasetFrame = QtWidgets.QFrame(self.DataInputDropdown)
        self.SaveDatasetFrame.setMinimumSize(QtCore.QSize(0, 44))
        self.SaveDatasetFrame.setMaximumSize(QtCore.QSize(16777215, 44))
        self.SaveDatasetFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SaveDatasetFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SaveDatasetFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SaveDatasetFrame.setObjectName("SaveDatasetFrame")
        self.frame = QtWidgets.QFrame(self.SaveDatasetFrame)
        self.frame.setGeometry(QtCore.QRect(0, -1, 601, 40))
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.DatasetExpand = QtWidgets.QPushButton(self.frame)
        self.DatasetExpand.setGeometry(QtCore.QRect(0, 0, 601, 40))
        self.DatasetExpand.setMinimumSize(QtCore.QSize(0, 40))
        self.DatasetExpand.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DatasetExpand.setFont(font)
        self.DatasetExpand.setStyleSheet("text-align: left")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/ExpandArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DatasetExpand.setIcon(icon1)
        self.DatasetExpand.setIconSize(QtCore.QSize(40, 40))
        self.DatasetExpand.setObjectName("DatasetExpand")
        self.label_16 = QtWidgets.QLabel(self.SaveDatasetFrame)
        self.label_16.setGeometry(QtCore.QRect(10, 39, 581, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.SaveDatasetFrame)
        self.label_17.setGeometry(QtCore.QRect(140, 160, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.RecordingLength = QtWidgets.QLabel(self.SaveDatasetFrame)
        self.RecordingLength.setGeometry(QtCore.QRect(320, 160, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.RecordingLength.setFont(font)
        self.RecordingLength.setObjectName("RecordingLength")
        self.frame_9 = QtWidgets.QFrame(self.SaveDatasetFrame)
        self.frame_9.setGeometry(QtCore.QRect(10, 100, 581, 51))
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.StartRecording = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.StartRecording.setFont(font)
        self.StartRecording.setStyleSheet("background-color: rgb(194, 232, 161);")
        self.StartRecording.setObjectName("StartRecording")
        self.horizontalLayout_3.addWidget(self.StartRecording)
        self.StopRecording = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.StopRecording.setFont(font)
        self.StopRecording.setStyleSheet("background-color: rgb(255, 170, 170);")
        self.StopRecording.setObjectName("StopRecording")
        self.horizontalLayout_3.addWidget(self.StopRecording)
        self.verticalLayout_21.addWidget(self.SaveDatasetFrame)
        self.DataBufferFrame = QtWidgets.QFrame(self.DataInputDropdown)
        self.DataBufferFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DataBufferFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DataBufferFrame.setObjectName("DataBufferFrame")
        self.verticalLayout_21.addWidget(self.DataBufferFrame)
        self.verticalLayout_4.addWidget(self.DataInputFrame)
        self.verticalLayout_3.addWidget(self.ColorMenuFrame)
        self.DepthMenuFrame = QtWidgets.QFrame(self.MenuPanel)
        self.DepthMenuFrame.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.DepthMenuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DepthMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DepthMenuFrame.setObjectName("DepthMenuFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.DepthMenuFrame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.DepthDropdownFrame = QtWidgets.QFrame(self.DepthMenuFrame)
        self.DepthDropdownFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DepthDropdownFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DepthDropdownFrame.setObjectName("DepthDropdownFrame")
        self.ColorDropdownFrame = QtWidgets.QFrame(self.DepthDropdownFrame)
        self.ColorDropdownFrame.setGeometry(QtCore.QRect(0, 50, 603, 500))
        self.ColorDropdownFrame.setMinimumSize(QtCore.QSize(603, 500))
        self.ColorDropdownFrame.setMaximumSize(QtCore.QSize(603, 500))
        self.ColorDropdownFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ColorDropdownFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ColorDropdownFrame.setObjectName("ColorDropdownFrame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.ColorDropdownFrame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.PointDistanceFrame = QtWidgets.QFrame(self.ColorDropdownFrame)
        self.PointDistanceFrame.setMinimumSize(QtCore.QSize(603, 44))
        self.PointDistanceFrame.setMaximumSize(QtCore.QSize(603, 44))
        self.PointDistanceFrame.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.PointDistanceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PointDistanceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PointDistanceFrame.setObjectName("PointDistanceFrame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.PointDistanceFrame)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.PointTitleFrame = QtWidgets.QFrame(self.PointDistanceFrame)
        self.PointTitleFrame.setMinimumSize(QtCore.QSize(0, 44))
        self.PointTitleFrame.setMaximumSize(QtCore.QSize(16777215, 44))
        self.PointTitleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PointTitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PointTitleFrame.setObjectName("PointTitleFrame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.PointTitleFrame)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.ExpandPoint = QtWidgets.QPushButton(self.PointTitleFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ExpandPoint.setFont(font)
        self.ExpandPoint.setStyleSheet("text-align: left")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Expand/ExpandArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.ExpandPoint.setIcon(icon2)
        self.ExpandPoint.setIconSize(QtCore.QSize(40, 40))
        self.ExpandPoint.setObjectName("ExpandPoint")
        self.verticalLayout_13.addWidget(self.ExpandPoint)
        self.verticalLayout_9.addWidget(self.PointTitleFrame)
        self.PointFunctionFrame = QtWidgets.QFrame(self.PointDistanceFrame)
        self.PointFunctionFrame.setStyleSheet("")
        self.PointFunctionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PointFunctionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PointFunctionFrame.setObjectName("PointFunctionFrame")
        self.label = QtWidgets.QLabel(self.PointFunctionFrame)
        self.label.setGeometry(QtCore.QRect(0, 10, 601, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.PointX = QtWidgets.QTextEdit(self.PointFunctionFrame)
        self.PointX.setGeometry(QtCore.QRect(250, 70, 104, 31))
        self.PointX.setObjectName("PointX")
        self.PointY = QtWidgets.QTextEdit(self.PointFunctionFrame)
        self.PointY.setGeometry(QtCore.QRect(410, 70, 104, 31))
        self.PointY.setObjectName("PointY")
        self.label_2 = QtWidgets.QLabel(self.PointFunctionFrame)
        self.label_2.setGeometry(QtCore.QRect(220, 80, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.PointFunctionFrame)
        self.label_3.setGeometry(QtCore.QRect(380, 80, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.PointFunctionFrame)
        self.label_4.setGeometry(QtCore.QRect(200, 120, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.PointDistance = QtWidgets.QLabel(self.PointFunctionFrame)
        self.PointDistance.setGeometry(QtCore.QRect(320, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PointDistance.setFont(font)
        self.PointDistance.setAutoFillBackground(False)
        self.PointDistance.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PointDistance.setText("")
        self.PointDistance.setObjectName("PointDistance")
        self.ClearPointDistance = QtWidgets.QPushButton(self.PointFunctionFrame)
        self.ClearPointDistance.setGeometry(QtCore.QRect(330, 160, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ClearPointDistance.setFont(font)
        self.ClearPointDistance.setObjectName("ClearPointDistance")
        self.CalculatePointDistance = QtWidgets.QPushButton(self.PointFunctionFrame)
        self.CalculatePointDistance.setGeometry(QtCore.QRect(190, 160, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.CalculatePointDistance.setFont(font)
        self.CalculatePointDistance.setObjectName("CalculatePointDistance")
        self.PointSelect = QtWidgets.QPushButton(self.PointFunctionFrame)
        self.PointSelect.setGeometry(QtCore.QRect(90, 70, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PointSelect.setFont(font)
        self.PointSelect.setObjectName("PointSelect")
        self.verticalLayout_9.addWidget(self.PointFunctionFrame)
        self.verticalLayout_8.addWidget(self.PointDistanceFrame)
        self.LineDistanceFrame = QtWidgets.QFrame(self.ColorDropdownFrame)
        self.LineDistanceFrame.setMinimumSize(QtCore.QSize(603, 44))
        self.LineDistanceFrame.setMaximumSize(QtCore.QSize(603, 44))
        self.LineDistanceFrame.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.LineDistanceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LineDistanceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LineDistanceFrame.setObjectName("LineDistanceFrame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.LineDistanceFrame)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.LineTitleFrame = QtWidgets.QFrame(self.LineDistanceFrame)
        self.LineTitleFrame.setMinimumSize(QtCore.QSize(0, 40))
        self.LineTitleFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.LineTitleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LineTitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LineTitleFrame.setObjectName("LineTitleFrame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.LineTitleFrame)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.ExpandLine = QtWidgets.QPushButton(self.LineTitleFrame)
        self.ExpandLine.setMinimumSize(QtCore.QSize(0, 40))
        self.ExpandLine.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ExpandLine.setFont(font)
        self.ExpandLine.setStyleSheet("text-align: left")
        self.ExpandLine.setIcon(icon2)
        self.ExpandLine.setIconSize(QtCore.QSize(40, 40))
        self.ExpandLine.setObjectName("ExpandLine")
        self.verticalLayout_14.addWidget(self.ExpandLine)
        self.verticalLayout_10.addWidget(self.LineTitleFrame)
        self.LineFunctionFrame = QtWidgets.QFrame(self.LineDistanceFrame)
        self.LineFunctionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LineFunctionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LineFunctionFrame.setObjectName("LineFunctionFrame")
        self.DrawLine = QtWidgets.QPushButton(self.LineFunctionFrame)
        self.DrawLine.setGeometry(QtCore.QRect(440, 90, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DrawLine.setFont(font)
        self.DrawLine.setObjectName("DrawLine")
        self.label_5 = QtWidgets.QLabel(self.LineFunctionFrame)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 571, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.LineX1 = QtWidgets.QTextEdit(self.LineFunctionFrame)
        self.LineX1.setGeometry(QtCore.QRect(150, 70, 104, 31))
        self.LineX1.setObjectName("LineX1")
        self.LineY1 = QtWidgets.QTextEdit(self.LineFunctionFrame)
        self.LineY1.setGeometry(QtCore.QRect(310, 70, 104, 31))
        self.LineY1.setObjectName("LineY1")
        self.LineX2 = QtWidgets.QTextEdit(self.LineFunctionFrame)
        self.LineX2.setGeometry(QtCore.QRect(150, 110, 104, 31))
        self.LineX2.setObjectName("LineX2")
        self.LineY2 = QtWidgets.QTextEdit(self.LineFunctionFrame)
        self.LineY2.setGeometry(QtCore.QRect(310, 110, 104, 31))
        self.LineY2.setObjectName("LineY2")
        self.label_8 = QtWidgets.QLabel(self.LineFunctionFrame)
        self.label_8.setGeometry(QtCore.QRect(110, 80, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.LineFunctionFrame)
        self.label_9.setGeometry(QtCore.QRect(110, 120, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.LineFunctionFrame)
        self.label_10.setGeometry(QtCore.QRect(270, 80, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.LineFunctionFrame)
        self.label_11.setGeometry(QtCore.QRect(270, 120, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.LineFunctionFrame)
        self.label_12.setGeometry(QtCore.QRect(20, 160, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.LineDistance = QtWidgets.QLabel(self.LineFunctionFrame)
        self.LineDistance.setGeometry(QtCore.QRect(150, 150, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LineDistance.setFont(font)
        self.LineDistance.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LineDistance.setText("")
        self.LineDistance.setObjectName("LineDistance")
        self.CalculateLineDistance = QtWidgets.QPushButton(self.LineFunctionFrame)
        self.CalculateLineDistance.setGeometry(QtCore.QRect(310, 160, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.CalculateLineDistance.setFont(font)
        self.CalculateLineDistance.setObjectName("CalculateLineDistance")
        self.ClearLineDistance = QtWidgets.QPushButton(self.LineFunctionFrame)
        self.ClearLineDistance.setGeometry(QtCore.QRect(440, 160, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ClearLineDistance.setFont(font)
        self.ClearLineDistance.setObjectName("ClearLineDistance")
        self.LinePoint1 = QtWidgets.QPushButton(self.LineFunctionFrame)
        self.LinePoint1.setGeometry(QtCore.QRect(10, 70, 89, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.LinePoint1.setFont(font)
        self.LinePoint1.setObjectName("LinePoint1")
        self.LinePoint2 = QtWidgets.QPushButton(self.LineFunctionFrame)
        self.LinePoint2.setGeometry(QtCore.QRect(10, 110, 89, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.LinePoint2.setFont(font)
        self.LinePoint2.setObjectName("LinePoint2")
        self.verticalLayout_10.addWidget(self.LineFunctionFrame)
        self.verticalLayout_8.addWidget(self.LineDistanceFrame)
        self.MultiplePointsFrame = QtWidgets.QFrame(self.ColorDropdownFrame)
        self.MultiplePointsFrame.setMinimumSize(QtCore.QSize(603, 44))
        self.MultiplePointsFrame.setMaximumSize(QtCore.QSize(603, 44))
        self.MultiplePointsFrame.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.MultiplePointsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MultiplePointsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MultiplePointsFrame.setObjectName("MultiplePointsFrame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.MultiplePointsFrame)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.MultipleTitleFrame = QtWidgets.QFrame(self.MultiplePointsFrame)
        self.MultipleTitleFrame.setMinimumSize(QtCore.QSize(0, 44))
        self.MultipleTitleFrame.setMaximumSize(QtCore.QSize(16777215, 44))
        self.MultipleTitleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MultipleTitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MultipleTitleFrame.setObjectName("MultipleTitleFrame")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.MultipleTitleFrame)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.ExpandMultiple = QtWidgets.QPushButton(self.MultipleTitleFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ExpandMultiple.setFont(font)
        self.ExpandMultiple.setStyleSheet("text-align: left")
        self.ExpandMultiple.setIcon(icon2)
        self.ExpandMultiple.setIconSize(QtCore.QSize(40, 40))
        self.ExpandMultiple.setObjectName("ExpandMultiple")
        self.verticalLayout_15.addWidget(self.ExpandMultiple)
        self.verticalLayout_11.addWidget(self.MultipleTitleFrame)
        self.MultipleFunctionFrame = QtWidgets.QFrame(self.MultiplePointsFrame)
        self.MultipleFunctionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MultipleFunctionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MultipleFunctionFrame.setObjectName("MultipleFunctionFrame")
        self.pushButton_3 = QtWidgets.QPushButton(self.MultipleFunctionFrame)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 10, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_11.addWidget(self.MultipleFunctionFrame)
        self.verticalLayout_8.addWidget(self.MultiplePointsFrame)
        self.RadiusFrame = QtWidgets.QFrame(self.ColorDropdownFrame)
        self.RadiusFrame.setMinimumSize(QtCore.QSize(603, 44))
        self.RadiusFrame.setMaximumSize(QtCore.QSize(603, 44))
        self.RadiusFrame.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.RadiusFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RadiusFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RadiusFrame.setObjectName("RadiusFrame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.RadiusFrame)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.RadiusTitleFrame = QtWidgets.QFrame(self.RadiusFrame)
        self.RadiusTitleFrame.setMinimumSize(QtCore.QSize(0, 44))
        self.RadiusTitleFrame.setMaximumSize(QtCore.QSize(16777215, 44))
        self.RadiusTitleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RadiusTitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RadiusTitleFrame.setObjectName("RadiusTitleFrame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.RadiusTitleFrame)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.ExpandRadius = QtWidgets.QPushButton(self.RadiusTitleFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ExpandRadius.setFont(font)
        self.ExpandRadius.setStyleSheet("text-align: left")
        self.ExpandRadius.setIcon(icon2)
        self.ExpandRadius.setIconSize(QtCore.QSize(40, 40))
        self.ExpandRadius.setObjectName("ExpandRadius")
        self.verticalLayout_16.addWidget(self.ExpandRadius)
        self.verticalLayout_12.addWidget(self.RadiusTitleFrame)
        self.RadiusFunctionFrame = QtWidgets.QFrame(self.RadiusFrame)
        self.RadiusFunctionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RadiusFunctionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RadiusFunctionFrame.setObjectName("RadiusFunctionFrame")
        self.pushButton_4 = QtWidgets.QPushButton(self.RadiusFunctionFrame)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 10, 89, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_12.addWidget(self.RadiusFunctionFrame)
        self.verticalLayout_8.addWidget(self.RadiusFrame)
        self.SpacerFrame = QtWidgets.QFrame(self.ColorDropdownFrame)
        self.SpacerFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.SpacerFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SpacerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SpacerFrame.setObjectName("SpacerFrame")
        self.verticalLayout_8.addWidget(self.SpacerFrame)
        self.label_13 = QtWidgets.QLabel(self.DepthDropdownFrame)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 603, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.label_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.DepthDropdownFrame)
        self.verticalLayout_3.addWidget(self.DepthMenuFrame)
        self.horizontalLayout.addWidget(self.MenuPanel)
        self.verticalLayout.addWidget(self.MainBody)
        self.MainFooter = QtWidgets.QFrame(self.centralwidget)
        self.MainFooter.setMaximumSize(QtCore.QSize(16777215, 50))
        self.MainFooter.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.MainFooter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFooter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFooter.setObjectName("MainFooter")
        self.verticalLayout.addWidget(self.MainFooter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1309, 22))
        self.menubar.setObjectName("menubar")
        self.menuMain_Page_Remove = QtWidgets.QMenu(self.menubar)
        self.menuMain_Page_Remove.setObjectName("menuMain_Page_Remove")
        self.menuSub_Page_Remove = QtWidgets.QMenu(self.menubar)
        self.menuSub_Page_Remove.setObjectName("menuSub_Page_Remove")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuMain_Page_Remove.menuAction())
        self.menubar.addAction(self.menuSub_Page_Remove.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ColorVideo.setText(_translate("MainWindow", "ColorVideo"))
        self.CVideoLabel.setText(_translate("MainWindow", "Color Video Input"))
        self.DepthVideo.setText(_translate("MainWindow", "DepthVideo"))
        self.DVideoLabel.setText(_translate("MainWindow", "Depth Video Input"))
        self.label_14.setText(_translate("MainWindow", "Data Input Controls"))
        self.LiveDataInput.setText(_translate("MainWindow", "Live Video"))
        self.SavedDataInput.setText(_translate("MainWindow", "Saved Data"))
        self.label_7.setText(_translate("MainWindow", "Start or stop streaming live color video and depth video data. "))
        self.StartColorVideo.setText(_translate("MainWindow", "Start"))
        self.StopColorVideo.setText(_translate("MainWindow", "Stop"))
        self.LiveVideoExpand.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Live Video Input</p></body></html>"))
        self.LiveVideoExpand.setText(_translate("MainWindow", "Live Video Input"))
        self.label_6.setText(_translate("MainWindow", "Select a saved dataset to load. Once the data is loaded the pictures \n"
"should appear and measurements can be taken. "))
        self.LoadDataButton.setText(_translate("MainWindow", "Choose Data"))
        self.SavedDataExpand.setText(_translate("MainWindow", "Saved Data Input"))
        self.SavePicExpand.setText(_translate("MainWindow", "Save Pictures"))
        self.SaveDepthPic.setText(_translate("MainWindow", "Save Color Picture"))
        self.SaveColorPic.setText(_translate("MainWindow", "Save Depth Picture"))
        self.label_15.setText(_translate("MainWindow", "Save a .jpg from either of the video streams \n"
" Note: depth data can not be obtained from a saved .jpg"))
        self.DatasetExpand.setText(_translate("MainWindow", "Save Dataset"))
        self.label_16.setText(_translate("MainWindow", "Record a dataset for later analysis. Data will be saved as a .bag file and\n"
" can be played in the \"Saved Data Input\" tab. "))
        self.label_17.setText(_translate("MainWindow", "Recording Length:   "))
        self.RecordingLength.setText(_translate("MainWindow", "00:00:00"))
        self.StartRecording.setText(_translate("MainWindow", "Start Recording"))
        self.StopRecording.setText(_translate("MainWindow", "Stop Recording"))
        self.ExpandPoint.setText(_translate("MainWindow", "Single Point Distance"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Enter (X,Y) coordinate or click a point on the video feeds then click calculate.<br/>  The center point is (320, 240).</p></body></html>"))
        self.PointX.setPlaceholderText(_translate("MainWindow", "320"))
        self.PointY.setPlaceholderText(_translate("MainWindow", "240"))
        self.label_2.setText(_translate("MainWindow", "X:"))
        self.label_3.setText(_translate("MainWindow", "Y:"))
        self.label_4.setText(_translate("MainWindow", "Distance(m):"))
        self.ClearPointDistance.setText(_translate("MainWindow", "Clear"))
        self.CalculatePointDistance.setText(_translate("MainWindow", "Calculate"))
        self.PointSelect.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Select Point</span></p></body></html>"))
        self.PointSelect.setText(_translate("MainWindow", "Select Point"))
        self.ExpandLine.setText(_translate("MainWindow", "Line Distance"))
        self.DrawLine.setText(_translate("MainWindow", "Draw Line"))
        self.label_5.setText(_translate("MainWindow", "Enter two X,Y coordinates or click the button to draw a line between two \n"
"points on the color video stream."))
        self.label_8.setText(_translate("MainWindow", "X1:"))
        self.label_9.setText(_translate("MainWindow", "X2:"))
        self.label_10.setText(_translate("MainWindow", "Y1: "))
        self.label_11.setText(_translate("MainWindow", "Y2:"))
        self.label_12.setText(_translate("MainWindow", "Distance (m):"))
        self.CalculateLineDistance.setText(_translate("MainWindow", "Calculate"))
        self.ClearLineDistance.setText(_translate("MainWindow", "Clear"))
        self.LinePoint1.setText(_translate("MainWindow", "Point 1:"))
        self.LinePoint2.setText(_translate("MainWindow", "Point 2:"))
        self.ExpandMultiple.setText(_translate("MainWindow", "Multiple Points Distance"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.ExpandRadius.setText(_translate("MainWindow", "Radius Distance"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.label_13.setText(_translate("MainWindow", "Measurement Controls"))
        self.menuMain_Page_Remove.setTitle(_translate("MainWindow", "Livestream Data"))
        self.menuSub_Page_Remove.setTitle(_translate("MainWindow", "Saved Data"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
